"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteUser = exports.deleteAccount = exports.removeUserFromAccountManually = exports.addUserToAccountManually = exports.createAccountManually = exports.checkExpiredInvitations = exports.checkExpiredAccounts = exports.suspendAccount = exports.demoteFromMaster = exports.promoteToMaster = exports.updateAccountLimits = exports.grantLifetimeAccess = exports.switchPlan = exports.transferOwnership = exports.removeMember = exports.suspendMember = exports.revokeInvitation = exports.acceptInvitation = exports.sendInvitation = exports.setupNewUser = void 0;
var auth_1 = require("./triggers/auth");
Object.defineProperty(exports, "setupNewUser", { enumerable: true, get: function () { return auth_1.setupNewUser; } });
var invitations_1 = require("./functions/invitations");
Object.defineProperty(exports, "sendInvitation", { enumerable: true, get: function () { return invitations_1.sendInvitation; } });
Object.defineProperty(exports, "acceptInvitation", { enumerable: true, get: function () { return invitations_1.acceptInvitation; } });
Object.defineProperty(exports, "revokeInvitation", { enumerable: true, get: function () { return invitations_1.revokeInvitation; } });
var members_1 = require("./functions/members");
Object.defineProperty(exports, "suspendMember", { enumerable: true, get: function () { return members_1.suspendMember; } });
Object.defineProperty(exports, "removeMember", { enumerable: true, get: function () { return members_1.removeMember; } });
Object.defineProperty(exports, "transferOwnership", { enumerable: true, get: function () { return members_1.transferOwnership; } });
var plans_1 = require("./functions/plans");
Object.defineProperty(exports, "switchPlan", { enumerable: true, get: function () { return plans_1.switchPlan; } });
Object.defineProperty(exports, "grantLifetimeAccess", { enumerable: true, get: function () { return plans_1.grantLifetimeAccess; } });
Object.defineProperty(exports, "updateAccountLimits", { enumerable: true, get: function () { return plans_1.updateAccountLimits; } });
var admin_1 = require("./functions/admin");
Object.defineProperty(exports, "promoteToMaster", { enumerable: true, get: function () { return admin_1.promoteToMaster; } });
Object.defineProperty(exports, "demoteFromMaster", { enumerable: true, get: function () { return admin_1.demoteFromMaster; } });
Object.defineProperty(exports, "suspendAccount", { enumerable: true, get: function () { return admin_1.suspendAccount; } });
var expiry_1 = require("./scheduled/expiry");
Object.defineProperty(exports, "checkExpiredAccounts", { enumerable: true, get: function () { return expiry_1.checkExpiredAccounts; } });
Object.defineProperty(exports, "checkExpiredInvitations", { enumerable: true, get: function () { return expiry_1.checkExpiredInvitations; } });
var master_1 = require("./functions/master");
Object.defineProperty(exports, "createAccountManually", { enumerable: true, get: function () { return master_1.createAccountManually; } });
Object.defineProperty(exports, "addUserToAccountManually", { enumerable: true, get: function () { return master_1.addUserToAccountManually; } });
Object.defineProperty(exports, "removeUserFromAccountManually", { enumerable: true, get: function () { return master_1.removeUserFromAccountManually; } });
// Account management
var accounts_1 = require("./functions/accounts");
Object.defineProperty(exports, "deleteAccount", { enumerable: true, get: function () { return accounts_1.deleteAccount; } });
Object.defineProperty(exports, "deleteUser", { enumerable: true, get: function () { return accounts_1.deleteUser; } });
//# sourceMappingURL=index.js.map